version: "3"
tasks:
  default:
    deps:
      - task: format
      - task: gha-lint
      - task: hadolint
  lint:
    deps:
      - task: gha-lint
      - task: hadolint
  gha-lint:
    vars:
      PINACT_VERSION: latest
      ACTIONLINT_VERSION: latest
      GHALINT_VERSION: latest
    cmds:
      - go run github.com/suzuki-shunsuke/pinact/v3/cmd/pinact@{{.PINACT_VERSION}} run
      - go run github.com/rhysd/actionlint/cmd/actionlint@{{.ACTIONLINT_VERSION}}
      - go run github.com/suzuki-shunsuke/ghalint/cmd/ghalint@{{.GHALINT_VERSION}} run
  hadolint:
    cmds:
      - docker run --rm -i -v {{.TASK_DIR}}/.hadolint.yml:/.config/hadolint.yaml ghcr.io/hadolint/hadolint < Dockerfile
      - docker run --rm -i -v {{.TASK_DIR}}/.hadolint.yml:/.config/hadolint.yaml ghcr.io/hadolint/hadolint < light.dockerfile
  format:
    vars:
      YAMLFMT_VERSION: v0.17.2
    cmds:
      - go run github.com/google/yamlfmt/cmd/yamlfmt@{{.YAMLFMT_VERSION}}
